// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbishrvgqkvjdjovgrkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiaXNocnZncWt2amRqb3Zncmt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTc2ODksImV4cCI6MjA2ODY5MzY4OX0.vIUG0-O5L8jsnP5H6pbKpHnd2Odg1JtU4AA844Of8o0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});